apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: haccp-postgres-data
  namespace: haccp
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 8Gi
