apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: haccp-cert
  namespace: haccp
spec:
  secretName: haccp-tls
  issuerRef:
    name: cloudflare-dns-issuer
    kind: ClusterIssuer
  dnsNames:
  - <YOUR_DOMAIN>
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days
  privateKey:
    algorithm: ECDSA
    size: 384
