apiVersion: v1
kind: Secret
metadata:
  name: haccp-secrets
  namespace: haccp
type: Opaque
stringData:
  DATABASE_HOST: "postgres-service"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "haccp"
  DATABASE_USER: "postgres"
  DATABASE_PASSWORD: "<your_password>"
