apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mysql
spec:
  capacity:
    storage: 128Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/data/k3s/mysql"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mongodb
spec:
  capacity:
    storage: 128Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/data/k3s/mongodb"
