apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:latest
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "password"
        ports:
        - containerPort: 3306
          name: mysql
        args:
          - "--ssl-ca=/mysql-certs/ca.pem"
          - "--ssl-cert=/mysql-certs/server-cert.pem"
          - "--ssl-key=/mysql-certs/server-key.pem"
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
        - name: cert-volume
          mountPath: /mysql-certs
          readOnly: true
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: pvc-mysql
      - name: cert-volume
        secret:
          secretName: mysql-certs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - image: mongo:latest
        name: mongo
        ports:
        - containerPort: 27017
          name: mongo
        volumeMounts:
        - name: mongo-data
          mountPath: /data/db
      volumes:
      - name: mongo-data
        persistentVolumeClaim:
          claimName: pvc-mongodb
