# K3s Kubernetes Deployment for Nextcloud
# https://nextcloud.com/

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-nextcloud-pvc
  namespace: apps
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 512Gi
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: vpa-nextcloud
  namespace: apps
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nextcloud
  updatePolicy:
    updateMode: Auto
  resourcePolicy:
    containerPolicies:
      - containerName: nextcloud
        minAllowed:
          cpu: "250m"
          memory: "1Gi"
        maxAllowed:
          cpu: "3000m"
          memory: "8Gi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
  namespace: apps
spec:
  selector:
    matchLabels:
      app: nextcloud
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      containers:
      - image: docker.io/library/nextcloud:latest
        name: nextcloud
        ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
        volumeMounts:
        - name: nextcloud-data
          mountPath: /var/www/html
      volumes:
      - name: nextcloud-data
        persistentVolumeClaim:
          claimName: longhorn-nextcloud-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: nextcloud-loadbalancer
  namespace: apps
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
    - port: 443
      targetPort: 443
  selector:
    app: nextcloud
